apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  labels:
    {{- include "fargate-sidecar-injector.labels" . | nindent 4 }}
  name: {{ include "fargate-sidecar-injector.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "fargate-sidecar-injector.name" . }}
  namespace: {{.Release.Namespace}}