{{- $tls := dict -}}
{{ $currTls := lookup "v1" "ConfigMap" "default" (include "fargate-sidecar-injector.name" .) }} 

{{- if and $currTls $currTls.data }}
{{- $_ := set $tls "ca.crt" (index $currTls.data "ca.crt") }}
{{- $_ := set $tls "prv.key" (index $currTls.data "prv.key") }}
{{- $_ := set $tls "cert.crt" (index $currTls.data "cert.crt") }}
{{- else }}
{{ $ca := genCA "fargate-sidecar-injector" 365 }}
{{ $cert := genSignedCert "fargate-sidecar-injector.default.svc" (list "127.0.0.1") (list "fargate-sidecar-injector" "fargate-sidecar-injector.default" "fargate-sidecar-injector.default.svc") 365 $ca }}
{{- $_ := set $tls "ca.crt" ($ca.Cert) }}
{{- $_ := set $tls "prv.key" ($cert.Key) }}
{{- $_ := set $tls "cert.crt" ($cert.Cert) }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fargate-sidecar-injector.name" . }}
  labels:
    {{- include "fargate-sidecar-injector.labels" . | nindent 4 }}
data:
  fargatesidecarinjector.conf: |-
    {
        "serve": {
        "port": "3003",
        "host": "",
        "tls":{
            "enabled": true,
            "cert": 
                "{{ index $tls "cert.crt" | indent 4 }}",
            "certKey": 
                "{{ index $tls "prv.key" | indent 4}}"
        } 
      }
    }