{{ $tls := fromYaml ( include "fargate-sidecar-injector.webhookCerts" . ) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fargate-sidecar-injector.name" . }}
  labels:
    {{- include "fargate-sidecar-injector.labels" . | nindent 4 }}
data:
  fargatesidecarinjector.conf: |-
    serve:
        port: 8443
        host: ""
        tls:
          enabled: true
          cert: {{  $tls.clientCert }}
          certKey: {{ $tls.clientKey }}
          ca: {{ $tls.caCert }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "fargate-sidecar-injector.name" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": -5"
  labels:
    {{- include "fargate-sidecar-injector.labels" . | nindent 4 }}
webhooks:
  - name: "fargate-sidecar-injector.default.svc"
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "fargate-sidecar-injector.name" . }}
        path: /mutate
      caBundle: {{ $tls.caCert }}
    rules:
      - apiGroups: [""]
        resources:
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE