{{- $tls := dict -}}
{{ $cert := lookup "v1" "ConfigMap" "default" (include "fargate-sidecar-injector.fullname" .) }}
{{- if and $cert $cert.data }}
{{- $_ := set $tls "ca.crt" (index $cert.data "ca.crt") }}
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "fargate-sidecar-injector.fullname" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    cert-manager.io/inject-ca-from: default/client
  labels:
    {{- include "fargate-sidecar-injector.labels" . | nindent 4 }}
webhooks:
  - name: "fargate-sidecar-injector.default.svc"
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    clientConfig:
      service:
        namespace: default
        name: {{ include "fargate-sidecar-injector.fullname" . }}
        path: /mutate
      {{- with $tls }}
      caBundle: {{ index $tls "ca.crt" }}
      {{- end }}
    rules:
      - apiGroups: [""]
        resources:
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE