apiVersion: v1
kind: Service
metadata:
  name: {{ include "fargate-sidecar-injector.name" . }}
  labels:
    {{- include "fargate-sidecar-injector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "fargate-sidecar-injector.selectorLabels" . | nindent 4 }}
