---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.fargate-injector.eks
  resources:
  - fargatesidecarconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.fargate-injector.eks
  resources:
  - fargatesidecarconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - cache.fargate-injector.eks
  resources:
  - fargatesidecarconfigs/status
  verbs:
  - get
  - patch
  - update
