apiVersion: v1
kind: ConfigMap
metadata:
  name: fargate-injector-sidecar-config
data: 
  default: |- # <- Fargate Profile
    spec:
      containers:
      - name: datadog
        image: datadog-operator:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /path/in/container
      volumes:
      - name: data
        configMap:
          name: myconfig